<table align="center" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Inclass-Lab  <br>(Week 3)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

## Table of Content

1. **[Chi-Square Test](#chisq)**
2. **[One-way ANOVA](#1way)**

**Import the required libraries**

In [1]:
# type your code here

import numpy as np
import pandas as pd
import scipy.stats as st

In [12]:
pip install scikit_posthocs

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  Created wheel for scikit-posthocs: filename=scikit_posthocs-0.6.7-py3-none-any.whl size=37903 sha256=b05a8d3752caa0fd7bcd5cc377fefd87e68f53c179efe822de4b02e15ee6af08
  Stored in directory: c:\users\hareeshkumar.s\appdata\local\pip\cache\wheels\59\a1\76\8954a8efb2e143534be5943de94a245c673b25b9ce71c3aab3
Successfully built scikit-posthocs


In [2]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2
from scipy.stats import chisquare

# function to perform post-hoc test
import statsmodels.stats.multicomp as mc

# import function to perform post-hoc
# install scikit_posthocs using "!pip install scikit_posthocs" 
import scikit_posthocs

### Let's begin with some hands-on practice exercises

<a id = "chisq"> </a>
## 1. Chi-Square Test

Use the data available in the CSV file `Employee_Attrition.csv` for questions 1 to 6.

In [3]:
df_emp = pd.read_csv('Employee_Attrition.csv')

df_emp.head(2)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  

[2 rows x 35 columns]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. A company in Los Angeles has three functional departments - Research and Development, Sales, and Human Resources. The company claims that the percentage of employees in these 3 departments is 55%, 35% and 10% respectively. Check the company's claim using p-value criteria. Consider a 5% level of significance.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [43]:
#Test For Goodness of Fit

In [4]:
alpha = 0.05

df_emp['Department'].value_counts()

Research & Development    961
Sales                     446
Human Resources            63
Name: Department, dtype: int64

In [5]:
obs_val = [961,446,63]
exp_val = [0.55 * len(df_emp),0.35 * len(df_emp),0.10*len(df_emp)]

In [7]:
tests_stats,p_value = st.chisquare(f_obs = obs_val,f_exp=exp_val)

p_value

2.2406437256053955e-19

In [8]:
if p_value > alpha:
    print('Fail to Reject Null Hypothesis')
else:
    print('Reject Null and Accept Alternate Hypothesis')

Reject Null and Accept Alternate Hypothesis


In [10]:
# The Company Claim is TRUE

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. The employees in an IT firm undergo an online assessment survey. The survey reveals that 20% of employees are least satisfied, 18% are fairly satisfied, 30% are moderately satisfied and 32% are highly satisfied with their job.Test the survey result with 90% confidence.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [12]:
df_emp['JobSatisfaction'].value_counts()

4    459
3    442
1    289
2    280
Name: JobSatisfaction, dtype: int64

In [14]:
alpha = 0.10
obs_val = [289,280,442,459]
exp_val = [0.20 * len(df_emp),0.18*len(df_emp),0.30*len(df_emp),0.32*len(df_emp)]

In [15]:
test_stats ,p_value = st.chisquare(f_obs=obs_val,f_exp=exp_val)

p_value

0.7386828586247451

In [16]:
if p_value > alpha:
    print('Fail to Reject Null Hypothesis')
else:
    print('Reject Null and Accept Alternate Hypothesis')

Fail to Reject Null Hypothesis


In [18]:
#Since p_value is > than alpha, The claim seems to be incorrect

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. The company claims that in the organization, 68% of employees are there with rare travelling, 20% with frequent travelling and 12% of employees does not need to travel for business. Check if the given data fits with the company's claimed distribution. Use the p-value technique with 99% confidence. </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [21]:
len_emp = len(df_emp)

In [20]:
df_emp['BusinessTravel'].value_counts()

Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: BusinessTravel, dtype: int64

In [22]:
alpha=0.01
obs_val = [1043,277,150]
exp_val =[0.68*len_emp,0.20*len_emp,0.12*len_emp]

In [23]:
test_stats ,p_value = st.chisquare(f_obs=obs_val,f_exp=exp_val)

p_value

0.0330688454314459

In [24]:
if p_value > alpha:
    print('Fail to Reject Null Hypothesis')
else:
    print('Reject Null and Accept Alternate Hypothesis')

Fail to Reject Null Hypothesis


In [25]:
#Since p_value is > than alpha, The claim seems to be incorrect

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Check whether travelling for work depends upon the job role of an employee. Use p-value criteria to test the dependence with 99% confidence.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [46]:
#H0: There is no association b/w two categorical vaiables

#H1: There is an association b/w categorical variables

In [29]:
table = pd.crosstab(df_emp['BusinessTravel'],df_emp['JobRole'])
table

JobRole            Healthcare Representative  Human Resources  \
BusinessTravel                                                  
Non-Travel                                15                4   
Travel_Frequently                         26               10   
Travel_Rarely                             90               38   

JobRole            Laboratory Technician  Manager  Manufacturing Director  \
BusinessTravel                                                              
Non-Travel                            28       12                      13   
Travel_Frequently                     51       13                      29   
Travel_Rarely                        180       77                     103   

JobRole            Research Director  Research Scientist  Sales Executive  \
BusinessTravel                                                              
Non-Travel                         6                  28               39   
Travel_Frequently                 12                  54               59   
Travel_Rarely                     62                 210              228   

JobRole            Sales Representative  
BusinessTravel                           
Non-Travel                            5  
Travel_Frequently                    23  
Travel_Rarely                        55

In [30]:
obs_val = table.values

obs_val

array([[ 15,   4,  28,  12,  13,   6,  28,  39,   5],
       [ 26,  10,  51,  13,  29,  12,  54,  59,  23],
       [ 90,  38, 180,  77, 103,  62, 210, 228,  55]], dtype=int64)

In [32]:
test_stat,p_value,dof,exp_val = st.chi2_contingency(obs_val)

test_stat,p_value,dof,exp_val

(11.987695596739206,
 0.7448263418408124,
 16,
 array([[ 13.36734694,   5.30612245,  26.42857143,  10.40816327,
          14.79591837,   8.16326531,  29.79591837,  33.26530612,
           8.46938776],
        [ 24.68503401,   9.79863946,  48.8047619 ,  19.22040816,
          27.32312925,  15.07482993,  55.02312925,  61.42993197,
          15.64013605],
        [ 92.94761905,  36.8952381 , 183.76666667,  72.37142857,
         102.88095238,  56.76190476, 207.18095238, 231.3047619 ,
          58.89047619]]))

In [33]:
if p_value > alpha:
    print('Fail to Reject Null Hypothesis')
else:
    print('Reject Null and Accept Alternate Hypothesis')

Fail to Reject Null Hypothesis


In [47]:
# Since Pvalue>alpha , we can conclude that There is no association between BusinessTravel and Job Role

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Is there any relationship between the attrition of an employee and his/her marital status? Use the critical value technique to test the relationship with 95% confidence. </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [48]:
#H0: There is no association b/w two categorical vaiables

#H1: There is an association b/w categorical variables

In [34]:
table = pd.crosstab(df_emp['Attrition'],df_emp['MaritalStatus'])
table

MaritalStatus  Divorced  Married  Single
Attrition                               
No                  294      589     350
Yes                  33       84     120

In [35]:

obs_val = table.values

obs_val

array([[294, 589, 350],
       [ 33,  84, 120]], dtype=int64)

In [39]:
test_stat,p_value,dof,exp_val = st.chi2_contingency(obs_val)

test_stat,p_value,dof,exp_val

(46.163676540848705,
 9.45551106034083e-11,
 2,
 array([[274.27959184, 564.49591837, 394.2244898 ],
        [ 52.72040816, 108.50408163,  75.7755102 ]]))

In [37]:
t_crit = st.chi2.isf(q=0.05,df=2)
t_crit

5.991464547107983

In [49]:
if abs(test_stat) <  abs(t_crit):
    print('Fail to Reject Null Hypothesis')
else:
    print('Accept Alternate Hypothesis')

Accept Alternate Hypothesis


In [50]:
# Since t_stats> t_crit, We can conclude that there is some relationship between the attrition of an employee 
# and his/her marital status

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Check whether travelling for the business depends on the gender of an employee. Use the p-value technique to test the claim with 90% confidence. </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [51]:
#H0: There is no association b/w two categorical vaiables

#H1: There is an association b/w categorical variables

In [33]:
table = pd.crosstab(df_emp['BusinessTravel'],df_emp['Gender'])

obs_val = table.values

obs_val

array([[ 49, 101],
       [117, 160],
       [422, 621]], dtype=int64)

In [41]:
test_stat,p_value,dof,exp_val = st.chi2_contingency(obs_val)

test_stat,p_value,dof,exp_val

(46.163676540848705,
 9.45551106034083e-11,
 2,
 array([[274.27959184, 564.49591837, 394.2244898 ],
        [ 52.72040816, 108.50408163,  75.7755102 ]]))

In [45]:
if p_value > alpha:
    print('Fail to Reject Null Hypothesis')
else:
    print('Reject Null and Accept Alternate Hypothesis')

Reject Null and Accept Alternate Hypothesis


In [52]:
# Since pvalue<alpha , we can conclude that travelling for the business depends on the gender of an employee

<a id = "1way"> </a>
## 5. One-way ANOVA

Use the data available in the CSV file `sales_emp.csv` for questions 7 to 11.

In [54]:
df_sale = pd.read_csv('sales_emp.csv')
df_sale.head(2)

Age BusinessTravel  DailyRate  DistanceFromHome  Education  \
0   36  Travel_Rarely       1218                 9          4   
1   39  Travel_Rarely        895                 5          3   

     EducationField  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction  \
0     Life Sciences              1              27                        3   
1  Technical Degree              1              42                        4   

   HourlyRate  ...  RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0          82  ...                         2             80                 0   
1          56  ...                         3             80                 1   

  TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                10                      4                3               5   
1                19                      6                4               1   

  YearsInCurrentRole YearsSinceLastPromotion  YearsWithCurrManager  
0                  3                       0                     3  
1                  0                       0                     0  

[2 rows x 31 columns]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Check whether we can use the given dataset to study the equality of average monthly income of sales executives with a different education background in the company. Use a p-value technique to test at a 5% level of significance.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [56]:
test_stats,p_value = st.shapiro(df_sale['MonthlyIncome'])
p_value

0.05732710659503937

In [57]:
# Shapiro test passed as p_value > alpha

In [58]:
# Equality of Variance

In [59]:
df_sale['EducationField'].value_counts()

Marketing           20
Life Sciences       16
Medical              8
Technical Degree     6
Other                4
Name: EducationField, dtype: int64

In [61]:
test_stat, p_value = st.levene(df_sale[df_sale['EducationField'] == 'Marketing']['MonthlyIncome'], 
                      df_sale[df_sale['EducationField'] == 'Life Sciences']['MonthlyIncome'], 
                      df_sale[df_sale['EducationField'] == 'Medical']['MonthlyIncome'], 
                      df_sale[df_sale['EducationField'] == 'Technical Degree']['MonthlyIncome'], 
                      df_sale[df_sale['EducationField'] == 'Other']['MonthlyIncome'])

p_value

0.23476859109336565

In [ ]:
# Leveve test passed as p_value > alpha

In [62]:
# we can use the given data set to study the equality of average monthly income of sales executives with a different education background in the company

 <table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Use the sales employees' dataset to test whether the average monthly income of sales executives with different education background is equal or not. Use a critical value method with 95% confidence.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [63]:
df_sale['EducationField'].nunique()

5

In [64]:
len(df_sale)

54

In [66]:
f_crit=st.f.isf(q=0.05,dfn=4,dfd=49)
f_crit
#dfn=m-1 *n-1

2.561124033899875

In [69]:
tstat,p=st.f_oneway(df_sale[df_sale['EducationField']=='Marketing']['MonthlyIncome'],
                df_sale[df_sale['EducationField']=='Life Sciences']['MonthlyIncome'],
                df_sale[df_sale['EducationField']=='Medical']['MonthlyIncome'],
                df_sale[df_sale['EducationField']=='Technical Degree']['MonthlyIncome'],
                df_sale[df_sale['EducationField']=='Other']['MonthlyIncome'])
tstat

0.9546031924978221

In [67]:
test_stat, p = st.f_oneway(df_sale[df_sale['EducationField'] == 'Marketing']['MonthlyIncome'], 
                      df_sale[df_sale['EducationField'] == 'Life Sciences']['MonthlyIncome'], 
                      df_sale[df_sale['EducationField'] == 'Medical']['MonthlyIncome'], 
                      df_sale[df_sale['EducationField'] == 'Technical Degree']['MonthlyIncome'], 
                      df_sale[df_sale['EducationField'] == 'Other']['MonthlyIncome'])
test_stat

0.9546031924978221

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Can we use the given data of sales executives to check the equality of the average daily rate for different types of business travellers? Use a p-value technique to test at a 1% level of significance.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [70]:
stat,p=st.shapiro(df_sale['DailyRate'])
p

0.040250398218631744

In [72]:
df_sale['BusinessTravel'].value_counts()

Travel_Rarely        18
Travel_Frequently    18
Non-Travel           18
Name: BusinessTravel, dtype: int64

In [74]:
stat,p=st.levene(df_sale[df_sale['BusinessTravel']=='Travel_Rarely']['DailyRate'],
                df_sale[df_sale['BusinessTravel']=='Non-Travel']['DailyRate'],
                df_sale[df_sale['BusinessTravel']=='Travel_Frequently']['DailyRate'])

p

0.23137904227432696

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Use the parametric test to check the equality of the average daily rate for all the types of business travelling. Use a p-value technique to test the data with 99% confidence.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [76]:
# type your code here

tets_stat, p = st.f_oneway(df_sale[df_sale['BusinessTravel'] == 'Travel_Rarely']['DailyRate'], 
                      df_sale[df_sale['BusinessTravel'] == 'Non-Travel']['DailyRate'], 
                      df_sale[df_sale['BusinessTravel'] == 'Travel_Frequently']['DailyRate'])

print(f"The p-value is :",p)
#reject the null hypothesis

The p-value is : 4.527131533131016e-06


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Find the types of business travel for which the average daily rate is different. Use a 1% level of significance.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [77]:
comp=mc.MultiComparison(data=df_sale['DailyRate'],groups=df_sale['BusinessTravel'])
post_hoc = comp.tukeyhsd(alpha=0.01)
post_hoc.summary()

<class 'statsmodels.iolib.table.SimpleTable'>